name: get_cli
description: Official CLI for GetX™ framework to build Flutter and Server Applications easily
version: 1.3.7
homepage: https://github.com/jonataslaw/get_cli

environment:
  sdk: '>=2.4.0 <3.0.0'

executables:
  get: get

dependencies:
  recase: ^3.0.0
  cli_menu: ^0.2.2
  archive: ^2.0.13
  ansicolor: ^1.0.2
  process_run: ^0.10.12+1
  http: ^0.12.2
  path: ^1.7.0
  yaml: ^2.2.1
  version: ^1.2.0
  intl: ^0.16.1
  cli_dialog: ^0.3.3
  json_ast: ^1.0.5
  dart_style:  ">=1.0.10 <2.0.0" 

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0