name: get_cli
description: The official CLI from Getx Framework to build Flutter Applications easily
version: 0.5.3
homepage: https://github.com/jonataslaw/get_cli

environment:
  sdk: '>=2.4.0 <3.0.0'

executables:
  get: get

dependencies:
  recase: ^3.0.0

  cli_menu: ^0.2.2
  archive: ^2.0.13
  ansicolor: ^1.0.2
  html: ^0.14.0+3
  process_run: ^0.10.12+1
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0