name: get_cli
description: A sample command-line application to manage flutter applications
version: 0.2.26
homepage: https://github.com/jonataslaw/get_cli

environment:
  sdk: '>=2.4.0 <3.0.0'

executables:
  get:

dependencies:
  recase: ^3.0.0
  http:
  cli_menu: ^0.2.2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
